SRC := */*.cpp */*/*.cpp
GPP_FLAGS := -std=gnu++0x -m32 -lxcb -Wwrite-strings -fpermissive
GPP_LIB := -L/home/hasan/Documents/VulkanSDK/1.0.26.0/x86_64/lib
GPP_INC := -I/home/hasan/Documents/VulkanSDK/1.0.26.0/x86_64/include -I/usr/include/AL

all:
	g++ $(SRC) $(GPP_FLAGS) $(GPP_LIB) $(GPP_INC)