
function(build_open_al OPENAL_DIR_VAR DEPENDENCIES_DIR)
    set(${OPENAL_DIR_VAR} ${DEPENDENCIES_DIR}/openal)
    set(${OPENAL_DIR_VAR} ${DEPENDENCIES_DIR}/openal PARENT_SCOPE)

    if(NOT EXISTS "${${OPENAL_DIR_VAR}}/CMakeLists.txt")
        message(STATUS "${${OPENAL_DIR_VAR}}/CMakeLists.txt was not found")
        message(FATAL_ERROR "The submodules were not downloaded! GIT_SUBMODULE was turned off or failed. Please update submodules and try again.")
    endif()

    set(ALSOFT_UTILS OFF CACHE BOOL "" FORCE)
    set(ALSOFT_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(ALSOFT_TESTS OFF CACHE BOOL "" FORCE)
    set(ALSOFT_CONFIG OFF CACHE BOOL "" FORCE)
    set(ALSOFT_HRTF_DEFS OFF CACHE BOOL "" FORCE)
    set(ALSOFT_AMBDEC_PRESETS OFF CACHE BOOL "" FORCE)
    set(ALSOFT_INSTALL OFF CACHE BOOL "" FORCE)
    set(LIBTYPE "STATIC")
    add_subdirectory("${${OPENAL_DIR_VAR}}")
    if (MSVC)
        target_compile_options(OpenAL PRIVATE /W0)
    else()
        target_compile_options(OpenAL PRIVATE -w)
    endif()
endfunction()
